name: Discord Notification

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord notification
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_PRCOMMENT }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"New comment on PR: ${{ github.event.issue.html_url }}"}' $WEBHOOK_URL
