name: Pull Request Open

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  PR-Open:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project dependencies
        run: |
          npm init -y
          npm install
          npm install axios
          npm install @actions/core
          npm install @actions/github
          
      - name: Analyze Pull Request
        run: node .github/scripts/pr-analyzer.js
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

